# Generated by Django 4.2.23 on 2025-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
