# Generated by Django 4.2.23 on 2025-08-06 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_on"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
