# Generated by Django 4.2.23 on 2025-08-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_comment_options_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
