# Generated by Django 4.2.23 on 2025-08-07 20:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_comment_updated_on_post_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
